web:  node server.js 

#knex migrate:rollback && knex migrate:latest && knex seed:run --specific=user.js && knex seed:run #--specific=mechanic.js && knex seed:run --specific=inspection.js && knex seed:run --specific=rating.js &&